server:
  port: 8084

spring:
  application:
    name: file-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_mart?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.231.200
      port: 6379
      password: 123456
      database: 0
      timeout: 5000ms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        ip: 127.0.0.1
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

# 文件存储配置
campus:
  file:
    storage-type: aliyun-oss
    local:
      base-path: ./uploads
      base-url: http://localhost:8084/uploads
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: 你的AccessKeyId
    access-key-secret: 你的AccessKeySecret
    bucket-name: 你的Bucket名

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.entity

logging:
  level:
    com.example: debug